.TH runtimetrim 1 "16 Aug 2023" "1.0.0-Man1.0" "RuntimeTrim"
.SH NAME
runtimetrim \- Trims your runtimes folder to just your architecture for .NET apps
.SH SYNOPSIS
nuglobal \<path\> [path2] ...
.SH DESCRIPTION
RuntimeTrim is a build tool for .NET projects that trims your runtimes folder to just your architecture for .NET apps. This is a useful application for Debian packaging so that you can debianize them without any trouble with the architecture support.
.SH AUTHOR
Aptivi (eoflaoevicecity@gmail.com)
