name: Build Project (Debian Package)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt update
          sudo apt purge dotnet*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev dotnet-sdk-7.0 devscripts debhelper-compat dput
        
      - name: Initialize offline package
        run: |
          chmod +x tools/initializeoffline.sh
          make debian-init-offline
        
      - name: Make original package
        run: |
          mv debian ..
          mv .github ..
          tar cfv ../runtimetrim_1.0.0.orig.tar .
          xz ../runtimetrim_1.0.0.orig.tar
          mv ../debian .

      - name: Build package
        run: |
          debuild --no-lintian -us -uc
          cp ../*.deb .
        
      - name: Upload package to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Debian-Package
          path: "*.deb"
