name: Push to PPA (amend with original source)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt update
          sudo apt purge dotnet*
          sudo apt autoremove
          sudo apt install curl locales-all cli-common-dev libunwind8-dev libcurl4-openssl-dev dotnet-sdk-7.0 devscripts debhelper-compat dput
        
      - name: Download original source
        run: |
          wget --output-document=../runtimetrim_1.0.0.orig.tar.xz https://launchpad.net/~eofla/+archive/ubuntu/aptivi-devapps/+sourcefiles/runtimetrim/1.0.0/runtimetrim_1.0.0.orig.tar.xz
          tar xf ../runtimetrim_1.0.0.orig.tar.xz .
          mv .github ..

      - name: Build source package
        run: debuild -S
        
      - name: Push to Launchpad
        run: dput ppa:eofla/aptivi-devapps ../runtimetrim_1.0.0*_source.changes
